# Generated by Django 3.0.4 on 2020-04-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('priority', models.IntegerField(choices=[(0, 'No priority'), (1, 'Low priority'), (2, 'Medium priority'), (3, 'High priority')], default=0, max_length=1)),
                ('closed', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=0, max_length=1)),
                ('skills', models.ManyToManyField(to='planning.Skills')),
            ],
        ),
    ]
