# Generated by Django 3.0.4 on 2020-04-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('creation_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=0)),
                ('priority', models.IntegerField(choices=[(0, 'No priority'), (1, 'Low priority'), (2, 'Medium priority'), (3, 'High priority')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name_plural': 'Tasks'},
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='closed',
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Closed')], default=0),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.IntegerField(choices=[(0, 'No priority'), (1, 'Low priority'), (2, 'Medium priority'), (3, 'High priority')], default=0),
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='skills',
        ),
        migrations.AddField(
            model_name='tasks',
            name='skills',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planning.Skills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='planning.Projects'),
            preserve_default=False,
        ),
    ]
