# Generated by Django 3.0.4 on 2020-04-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_auto_20200409_1754'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('worker', 'date', 'shift')},
        ),
        migrations.AlterUniqueTogether(
            name='workerskills',
            unique_together={('worker', 'skill')},
        ),
    ]
