# Generated by Django 3.0.4 on 2020-04-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_auto_20200409_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='workplaces',
            field=models.FloatField(default=1),
        ),
    ]
