# Generated by Django 3.0.4 on 2020-04-18 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0007_auto_20200418_1239'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('worker', 'date')},
        ),
    ]
