# Generated by Django 3.0.4 on 2020-04-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0008_auto_20200418_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='shift',
        ),
        migrations.AddField(
            model_name='availability',
            name='shift',
            field=models.ManyToManyField(to='planning.Shifts'),
        ),
    ]
