# Generated by Django 3.0.4 on 2020-04-20 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_workers_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.Skills'),
        ),
    ]
